apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-data
  namespace: uptime-kuma
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: uptime-data
  hostPath:
    path: '/your_local_folder/uptime'
