apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-data
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: uptime-data
  hostPath:
    # Edit this to a point to a local folder you want to use for persistance
    path: '/your_local_folder/uptime'
